{{- if (not .Values.basicAuthSecrets.existingSecrets) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openfaas-cron-connector.basic-auth-secrets-name" . | quote }}
  labels:
{{ include "openfaas-cron-connector.labels" . | indent 4 }}
data:
  {{- range $key, $value := .Values.basicAuthSecrets.values }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
