apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openfaas-cron-connector.fullname" . }}
  labels:
    {{- include "openfaas-cron-connector.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "openfaas-cron-connector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- include "openfaas-cron-connector.linkerdAnnotations" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "openfaas-cron-connector.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "openfaas-cron-connector.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: CONNECTOR_NAME
              value: {{ .Values.settings.connector_name | quote }}
            - name: FAAS_GATEWAY
              value: {{ .Values.settings.faas_gateway | quote }}
            - name: GATEWAY_SSL
              value: {{ .Values.settings.gateway_ssl | quote  }}
              {{ if .Values.settings.faas_gateway_user }}
            - name: FAAS_GATEWAY_USER
              value: {{ .Values.settings.faas_gateway_user | quote }}
              {{ end }}
              {{ if .Values.settings.faas_gateway_pass }}
            - name: FAAS_GATEWAY_PASS
              value: {{ .Values.settings.faas_gateway_pass | quote }}
              {{ end }}
            - name: TIMEOUT
              value: {{ .Values.settings.timeout | quote }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /var/secrets
              name: auth
              readOnly: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: auth
          secret:
            defaultMode: 420
            secretName: {{ include "openfaas-cron-connector.basic-auth-secrets-name" . | quote }}
