name: Build Docker Image

on:
  push:
    tags:
      - '*'
    paths-ignore:
      - 'deploy/**'
      - '.github/**'
  workflow_dispatch:
    inputs:
      git-tag:
        description: The Git Tag to run the workflow on.
        required: true

env:
  DOCKER_USERNAME: _json_key
  DOCKER_PASSWORD: ${{ secrets.GCP_SA_KEY_JSON }}
  DOCKER_REGISTRY_URL: https://gcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Default Checkout
      uses: actions/checkout@v1
      if: github.event.inputs.git-tag == ''
    - name: Workflow Dispatch Checkout
      uses: actions/checkout@v1
      if: github.event.inputs.git-tag != ''
      with:
        ref: ${{ github.event.inputs.git-tag }}
    - name: Build the Docker image
      run: |
        docker build \
        --file Dockerfile \
        --tag gcr.io/platform-235214/openfaas-cron-connector:${GITHUB_REF/refs\/tags\//} \
        --build-arg VCS_REF=`git rev-parse --short HEAD` \
        --build-arg VERSION=${GITHUB_REF/refs\/tags\//} \
        --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
        .
    - name: Docker Login
      run: docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}" "${DOCKER_REGISTRY_URL}"
    - name: Docker Push
      run: docker push gcr.io/platform-235214/openfaas-cron-connector:${GITHUB_REF/refs\/tags\//}
    - name: Tag the docker image to latest tag
      run: docker tag gcr.io/platform-235214/openfaas-cron-connector:${GITHUB_REF/refs\/tags\//} gcr.io/platform-235214/openfaas-cron-connector:latest
    - name: Push the latest Docker image
      run: docker push gcr.io/platform-235214/openfaas-cron-connector:latest
