name: "Helm chart CI"

on:
  pull_request:
    branches:
      - '*'
    paths:
      - 'deploy/**'
  push:
    branches:
      - master
    paths:
      - 'deploy/**'
env:
  HELM_CHART_PATH: './deploy/openfaas-cron-connector'
  HELM_CHART_REPO_NAME: 'ratehub'
  HELM_CHART_REPO_URL: 'cm://helm.ratehub.dev'

jobs:
  helm:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codebase'
        uses: actions/checkout@v3

      - name: 'Setup helm'
        id: install
        uses: azure/setup-helm@v3
        with:
          version: 'v3.9.0'

      - name: Lint helm chart
        run: |
          helm lint "${HELM_CHART_PATH}"

      - name: Install helm push
        run: |
          helm plugin install https://github.com/chartmuseum/helm-push

      - name: Add helm.ratehub.dev
        env:
          HELM_REPO_USERNAME: ${{ secrets.RATEHUB_HELM_USER }}
          HELM_REPO_PASSWORD: ${{ secrets.RATEHUB_HELM_PASS }}
        run: |
          helm repo add "${HELM_CHART_REPO_NAME}" "${HELM_CHART_REPO_URL}"

      - name: Publish helm chart
        if: github.ref == 'refs/heads/master'
        env:
          HELM_REPO_USERNAME: ${{ secrets.RATEHUB_HELM_USER }}
          HELM_REPO_PASSWORD: ${{ secrets.RATEHUB_HELM_PASS }}
        run: |
          helm cm-push "${HELM_CHART_PATH}" "${HELM_CHART_REPO_NAME}"
